package com.comcast.customer;

import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String cusName;
	private java.lang.String cusAddress;
	private java.lang.String cusEmail;
	private java.lang.Integer cusPhone;
	private java.lang.String typeOfEvent;
	private Date eventDate;
	private java.lang.String eventLocation;

	public Customer() {
	}

	public java.lang.String getCusName() {
		return this.cusName;
	}

	public void setCusName(java.lang.String cusName) {
		this.cusName = cusName;
	}

	public java.lang.String getCusAddress() {
		return this.cusAddress;
	}

	public void setCusAddress(java.lang.String cusAddress) {
		this.cusAddress = cusAddress;
	}

	public java.lang.String getCusEmail() {
		return this.cusEmail;
	}

	public void setCusEmail(java.lang.String cusEmail) {
		this.cusEmail = cusEmail;
	}

	public java.lang.Integer getCusPhone() {
		return this.cusPhone;
	}

	public void setCusPhone(java.lang.Integer cusPhone) {
		this.cusPhone = cusPhone;
	}

	public java.lang.String getTypeOfEvent() {
		return this.typeOfEvent;
	}

	public void setTypeOfEvent(java.lang.String typeOfEvent) {
		this.typeOfEvent = typeOfEvent;
	}

	public java.lang.String getEventLocation() {
		return this.eventLocation;
	}

	public void setEventLocation(java.lang.String eventLocation) {
		this.eventLocation = eventLocation;
	}

	public java.util.Date getEventDate() {
		return this.eventDate;
	}

	public void setEventDate(java.util.Date eventDate) {
		this.eventDate = eventDate;
	}

	public Customer(java.lang.String cusName, java.lang.String cusAddress,
			java.lang.String cusEmail, java.lang.Integer cusPhone,
			java.lang.String typeOfEvent, java.util.Date eventDate,
			java.lang.String eventLocation) {
		this.cusName = cusName;
		this.cusAddress = cusAddress;
		this.cusEmail = cusEmail;
		this.cusPhone = cusPhone;
		this.typeOfEvent = typeOfEvent;
		this.eventDate = eventDate;
		this.eventLocation = eventLocation;
	}

}